### ISSUE TITLE
Holiday File Issue

### ISSUE THREAD

**Issue by cotton1234** [BennyThadikaran/eod2#11]
Hello,

There seems to be another issue related to holiday.json.

   {
      "tradingDate": "28-Jun-2023",
      "weekDay": "Wednesday",
      "description": "Bakri Id",
      "Sr_no": 10
   },

This is the holiday.json which is incorrect as the holiday was changed yesterday by NSE.

I have fixed it by removing the file and it downloaded the same but try to see if you can get the latest file everyday.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
Hi, Saurabh, Thanks for raising this issue. I see its a problem on my own local repo as well. 

A better solution: If there is a holiday as per holiday.json, we re-download the file to verify it.
Let me see how this works out. I'll push a fix by evening if all works well.

**Comment by BennyThadikaran** [comment]
I have made the changes and code is working correctly. Changes are in `getHolidayList` and `checkForHolidays` on `defs.py`

If you have the latest changes from the repo all you need to do is run `git pull` and code changes will be updated. Run `py init.py` to get the latest data.
 
```bash
Downloading Files
Starting Data Sync
EOD sync complete
Delivery Data updated
Delivery sync complete
Index sync complete.
Makings adjustments for splits and bonus
Cleaning up files
2 files deleted
28 Jun 2023: Done
----------------------------------------------------
All Up To Date. Check again after 7pm for today's EOD data
```

**Comment by cotton1234** [comment]
Thanks Benny. Works fine.
