### ISSUE TITLE
Data update issue 4th June'24

### ISSUE THREAD

**Issue by rohit1409** [BennyThadikaran/eod2#144]
Hi Benny, not sure what's not right.. files are available at NSE page for eod however code throwing back this error.. please have a look whenever convenient. Tx 

***********************

INFO: Updating NSE EQUITY actions
INFO: Updating NSE SME actions
INFO: Downloading Files
WARNING: NSE file is unavailable or not yet updated.

***********************

**Comment by BennyThadikaran** [comment]
You can try it now. Its all working fine. Both Equity and Indices bhavcopy are required to commence update. Usually try it again after an hour.

**Comment by rohit1409** [comment]
As prompt as ever, thanks Benny !
