### ISSUE TITLE
8th July_Data Issue

### ISSUE THREAD

**Issue by rohit1409** [BennyThadikaran/eod2#158]
Hi Benny, 

I could see BhavCopy available at NSE site, but script seems to be having some fetching issues, any idea why so?

INFO: Downloading Files
INFO: Sat, 06 Jul 2024: Market Closed
----------------------------------------------------
INFO: Downloading Files
WARNING: NSE file is unavailable or not yet updated.

Thanks,
Rohit

**Comment by BennyThadikaran** [comment]
This is a common error. Both the bhavcopy and indices report should be available to continue sync.

Just try again now its working.

**Comment by rohit1409** [comment]
![Screenshot 2024-07-08 230941](https://github.com/BennyThadikaran/eod2/assets/53401079/95b59acb-f172-4693-abda-b96b6d26d769)

Ah ok, then probably indices not ready, may be ill check in morning again. Thanks

**Comment by rohit1409** [comment]
Hi Benny, today also same issue coming, can you suggest something for me to troubleshoot this, not sure as script runs, it makes connection with NSE website as it states 6th July Market Close.. but then it stating the data is not available.

INFO: Downloading Files
INFO: Sat, 06 Jul 2024: Market Closed
----------------------------------------------------
INFO: Downloading Files
WARNING: NSE file is unavailable or not yet updated.
[Finished in 2.3s]

Any suggestion welcomed !

**Comment by rohit1409** [comment]
![Screenshot 2024-07-09 205212](https://github.com/BennyThadikaran/eod2/assets/53401079/098d0a6f-f020-4d77-8769-e956d34cd3c0)


Could this be culprit.. I just read on NSE Website

Discontinued w.e.f July 08,2024. Refer NSE Circular No. 62424 dated June 12, 2024. Switch to CM-UDiFF Common Bhavcopy Final(zip)

**Comment by BennyThadikaran** [comment]
Oh yes. Sorry i didnt realise you're running the older version. I have already posted an update, [see here](https://github.com/BennyThadikaran/eod2?tab=readme-ov-file#important)

Just update your script to the latest version and it should work again.

**Comment by rohit1409** [comment]
Houston we are back online !

Thanks Benny, issued addressed.
