### ISSUE TITLE
Conversion

### ISSUE THREAD

**Issue by utsadey** [BennyThadikaran/eod2#159]
I tried many programs in python to convert the downloaded CSV data to metastock or text file. But it's not working. The data is not working with metastock. If you kindly help with that I'll be grateful.

**Comment by BennyThadikaran** [comment]
Hi Utsadey,

Do you have sample file that uploads into Metastock or some description of the file format?

I dont know anything about MetaStock so you'll need to help with information and testing. Also I'm not free for next few weeks but I will consider it.
