### ISSUE TITLE
defs.defs - Failed to download holidays

### ISSUE THREAD

**Issue by cotton1234** [BennyThadikaran/eod2#193]
Hello Benny,

Getting the following error today (Mon Oct 14 ).

(.venv) saurabhgarg@MacBook-Pro src % python3 init.py
sh: color: command not found
WARNING: 14-10-2024 20:55 - defs.defs - Failed to download holidays - Expecting value: line 1 column 1 (char 0)

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
Update nse package to latest. `pip install -U nse` to resolve the issue.

`nse` package headers mentioned gzip, brotli as acceptable compression formats. Brotli is not supported by `requests` library by default (requires external library to add support).

NSE servers used to prefer gzip compression but now prefers Brotli. I have removed Brotli from the headers.

**Comment by rohit1409** [comment]
Working fine now, Thanks B, Cheers !
