### ISSUE TITLE
Indices Data

### ISSUE THREAD

**Issue by cotton1234** [BennyThadikaran/eod2#27]
Hello Benny,

I was looking at the eod daily folder and could find only some indices and not all the indices.

![image](https://github.com/BennyThadikaran/eod2/assets/11193250/9df4a256-8d0d-48fe-82c2-9111be74c785)

where as in the file ind_close_all_01082023.csv there are lot of indices. 

![image](https://github.com/BennyThadikaran/eod2/assets/11193250/7ad651f0-12d4-47e9-a26e-1c8ddb662120)

Can i define somewhere what all indices i need to sync.

Also i am planning to use the same logic for downloading stock data from BSE as some stocks are only listed on it.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
In the eod2_data folder there is a sector_watchlist.csv file. It has the entire list of Indices that are synced. If you need additional indices you can add them to this file.

If you do edit this file, take a backup of the changes as any pull request will overwrite your edits.

Also you wont have historic data. That functionality is not included. It will be synced on a daily basis.

**Comment by BennyThadikaran** [comment]
If you have my latest code, you can create a `user.json` in the `defs` folder. I can update the code so you can define a list of additional indices in user.json. That way your changes wont get overwritten. If you can keep this issue open i will update the code and get back by tomorrow.

**Comment by cotton1234** [comment]
Sure Benny will sync the new one once you update.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
Create a user.json in defs folder like below:
```javascript
{
  "ADDITIONAL_INDICES": ["Nifty 200"]
}
```
Indices names are case sensitive, check the nse indices report for correct casing. You will get a key error is casing is incorrect.

**Comment by cotton1234** [comment]
> Create a user.json in defs folder like below:
> 
> ```js
> {
>   "ADDITIONAL_INDICES": ["Nifty 200"]
> }
> ```
> 
> Indices names are case sensitive, check the nse indices report for correct casing. You will get a key error is casing is incorrect.
> 
> You can run `py init.py c` to print configuration. If everything is correct, you will see the ADDITIONAL_INDICES with the index names printed as a list.
> 
> ```shell
> EOD2 | Version: 3.0.1
> AMIBROKER: False
> AMI_UPDATE_DAYS: 365
> PLOT_DAYS: 180
> PLOT_AVG_DAYS: 60
> LOOKUP_AVG_DAYS: 60
> LOOKUP_DAYS: 15
> WATCH: watchlist.csv
> IT: it.csv
> BANK: bank.csv
> ADDITIONAL_INDICES: ['Nifty 200']
> ```

Thanks Benny, I was able to pull the same and added some new index which I need to monitor.

Saurabh
