### ISSUE TITLE
Special Session of 20 Jan 2024 Not getting updated

### ISSUE THREAD

**Issue by cotton1234** [BennyThadikaran/eod2#93]
Hello Benny,

Today session 20 Jan 2024 is not getting downloaded and saying All upto date.
Can you pls check the same.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
Hi Saurabh, 

This has been fixed and i have also taken care of 22nd Jan 2024 holiday by forcing an update of the holiday list. This is a temporay fix. I will monitor on Monday if any issues crop up.

EOD2 will now attempt to download reports on Saturday. 

- If attempt fails, check if user is syncing for same day, exit and inform the user to check NSE website if report is available and try again.
- Else continue to sync the next available date, without exiting

**Comment by cotton1234** [comment]
Thanks Benny
