### ISSUE TITLE
Error Coming in Making Adjustments - KeyError(datetime.datetime(2024,1,25,0,0)

### ISSUE THREAD

**Issue by cotton1234** [BennyThadikaran/eod2#95]
Hello Benny,

Today while syncing error is coming.
**Error:**

saurabhgarg@MacBook-Pro src % python3 --version
Python 3.9.6
saurabhgarg@MacBook-Pro src % python3 init.py
sh: color: command not found
Downloading Files
Starting Data Sync
EOD sync complete
Index sync complete.
Makings adjustments for splits and bonus
Error while making adjustments. KeyError(datetime.datetime(2024, 1, 25, 0, 0))
All adjustments have been discarded.
Rolling back changes from 2024-01-25: /Users/saurabhgarg/shivshakti/eod2/src/eod2_data/daily
Rollback successful
saurabhgarg@MacBook-Pro src %

Can you pls check your repo.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
Hi Saurabh, Thanks for taking the time. I have the same issue on my side, looking into it. :relieved:

**Comment by cotton1234** [comment]
Fine Benny

**Comment by cotton1234** [comment]
Pulled the new code and its working fine now. 
Thanks Benny.
